### ISSUE TITLE
[Question] Unique Identifier for generated Container

### ISSUE THREAD

**Issue by LuisRizo** [electrode-io/electrode-native#1081]
Is there a way that our native iOS team can tell when a regenerated container actually has any changes or is the right container?

What I'm thinking is having the containerVersion embedded in the generated Info.plist of the generated `ElectrodeContainer`. Currently, it always displays `1.0` and I was wondering if that is meant to change to match the containerVersion in the cauldron, or if there is any other way to tell two containers apart with an easy to understand unique identifier

**Comment by belemaire** [comment]
Hi @LuisRizo 

You are right when you are stating that `ElectrodeContainer` does not embed the Container version in it's `info.plist` file. This is something that we are planning to work on in a future version of Electrode Native.

Meanwhile, we don't really have faced such an issue yet, because internally we are publishing the iOS Container to a git repository (using the `git` publisher of Electrode Native) which creates a git tag for each version of the Container and using Carthage to include a specific version (pointing to a specific git version tag) of the Container in the mobile application build. So looking at the Carthage file in the mobile application, we have a way to know which version of the Container is currently used, and using github we can easily see diffs between different container versions by just comparing the tags.

But having the version inside the `info.plist` is a thing we need as well, I'll create a new issue just to track this.

**Comment by belemaire** [comment]
Closing this one in favor of https://github.com/electrode-io/electrode-native/issues/1083

**Comment by LuisRizo** [comment]
Having it in the `Info.plist` helps for people that are not using Carthage in their native apps (me!). Thank you for help
