### ISSUE TITLE
Code Push Target Version use Container Version?

### ISSUE THREAD

**Issue by devpascoe** [electrode-io/electrode-native#1091]
I am fairly sure the answer is no since its handled by appcenter but can the Code Push Target Version use the Container Version instead of the binary app version installed?

I'd love to be able to code push to apps using the framework where those apps i do not have full control over their Versioning.

**Comment by devpascoe** [comment]
🤔

**Comment by belemaire** [comment]
Hi @devpascoe 

Short story ... unfortunately, as you mentioned, it's handled by app center, we have no way to change this. 
As seen in the [documentation of code push cli](https://github.com/Microsoft/code-push/tree/master/cli), the version that is being used, is the native application version 

| Platform               | Source of app store version                                                  |
|------------------------|------------------------------------------------------------------------------|
| React Native (Android) | The `android.defaultConfig.versionName` property in your `build.gradle` file |
| React Native (iOS)     | The `CFBundleShortVersionString` key in the `Info.plist` file                |

What this means, is that when the mobile application is asking the CodePush server for an update, it will send the native app version as a reference. This is something we can't control.

Long story ... if you're really adventurous, you might consider using our [open source CodePush server](https://github.com/electrode-io/electrode-ota-server). We are using this server for some of our mobile applications, instead of Microsoft AppCenter. Because Microsoft Code Push server is closed source (but command line CLI and mobile CLI are -were- open source), and we needed more control, we had to come up with our own server, fully compatible with Microsoft one.

This is probably far stretched for now, and I wouldn't recommend it just yet as our server is not -yet- widely documented or used, so it will require a lot of involvement to set it up. But because we have full control on it, we can implement new custom features to it. For example we'll release differential bundle CodePush soon, which will allow pushing only the changes of the JS bundle instead of the full bundle, greatly reducing pushed bundle size. We will also open source our mobile CLI libraries soon for this server. But if what you need is a strong requirement, then this it'll be the only way to go given that we have no way to update Microsoft AppCenter server code ;)

That being said, could you please elaborate a little bit on your intended use case for this ? It's not ultra clear what you'd like to achieve, I'll be interested to know more about it.

**Comment by devpascoe** [comment]
Again thank you for the info. My scenario is a little unique. 
Building a white label social network. Looking to roll out managed apps that we build. And a Carthage framework for custom integration with existing app projects. 

Ideally i’d like the Code Push to be in line with the Container framework version, not the binary. But I can get away with it likely by not supporting code push for those custom integrations (by not giving instructions for Code Push during initialization).

**Comment by LuisRizo** [comment]
You could theoretically use the `appOverrideVersion` method available on the Objective-C API of CodePush (https://github.com/Microsoft/react-native-code-push/blob/master/docs/api-ios.md) and pass it the CFBundleShortVersionString of the ElectrodeContainer that is now generated based on the Container Version (Thanks to this https://github.com/electrode-io/electrode-native/issues/1083) and also use the `-t` argument on the `ern code-push release` command to target the Container.

It's more of a hack than a solution but just to let others know that it is a possibility (at least on iOS, haven't looked on this for Android)

**Comment by devpascoe** [comment]
Super interesting, so you'd might need to...
- create your own code push plugin forked from https://github.com/electrode-io/electrode-native-manifest/blob/master/plugins/ern_v0.13.0%2B/react-native-code-push_v1.17.0%2B/ElectrodeCodePushConfig.m
- Sub class CodePush and have ElectrodeCodePushConfig.m reference that subclass instead of directly
- override in subclass `(void)overrideAppVersion:(NSString *)appVersionOverride` with whatever code you like that gets you the version (eg, read version in plist of .framework https://stackoverflow.com/questions/24538215/get-version-number-of-ios-universal-framework-in-client)

**Comment by belemaire** [comment]
Closing this one now, feel free to reopen if needed.
