### ISSUE TITLE
Carthage build failure due to missing assets directory

### ISSUE THREAD

**Issue by devpascoe** [electrode-io/electrode-native#1092]
Creating a fresh cauldron, miniapp, nativeapp and container (git bitbucket). Running: `carthage update --platform ios` fails to build however does checkout successfully. The culprit is that i need to create a directory under ElectrodeContainer/Libraries/MiniApp called assets. Once that empty directory exists (locally) i can then re-run `carthage update --platform ios` with success.

Perhaps a workaround is to add an image etc.. within one of the miniapp's to be included. But it'd be nice to not have to remember that.

Thanks.

**Comment by jduthon** [comment]
Hey @devpascoe ,

Which version are you using?
Could it be related to https://github.com/electrode-io/electrode-native/issues/1064 ?
If so it should normally be fixed from 0.29.4 :)

**Comment by jduthon** [comment]
Just ran into the same error, so different issue.

**Comment by devpascoe** [comment]
Running v0.29.8

**Comment by devpascoe** [comment]
Also `npm install -g electrode-native && ern` installs 0.29.8 - not latest (currently 0.29.9) so npm might need latest version published.

**Comment by devpascoe** [comment]
To force using latest should i be running
ern platform use latest

or really just wait for npm to update with latest?

**Comment by jduthon** [comment]
First: latest will **not** solve this problem.
Not sure what is the recommended way to update but `ern platform use latest` provides better result IMHO, it will currently get you on `0.29.9`

**Comment by belemaire** [comment]
@devpascoe 
First, as a quick clarification, `npm install -g electrode-native && ern` is to be used solely for a first time install of Electrode Native as it's used to install the global CLI (`electrode-native` module) along with the latest version of the local CLI (`ern`). 
Once you have access to the `ern` command, you can just use `ern platform use latest` as suggested by @jduthon to install and switch to the latest version of `ern` local CLI that is available. Or `ern platform use <version>` which will install a specific version (if not installed already) and switch to this version. You can see all available / installed / activated versions by using `ern platform versions` command.

As for the issue in itself, regarding `assets`, looks like a regression was introduced recently, as we fixed the problem initially through #1064 as mentioned by @jduthon

Will look into it and come back to you.

**Comment by devpascoe** [comment]
Amazing amazing thank you

**Comment by belemaire** [comment]
I am not able to reproduce locally, but I think it has to do with the git publication.  
#1064 properly fixes the issue for container generation, meaning that locally created containers, will properly have the assets directory. Meaning that `run-ios` also works fine for freshly created MiniApps. However, I can see in Electrode Native code, that after performing Container cleanup during generation (if a Container was already present in output directory we remove some directories), we recreate the `assets` directory as an empty directory (if no assets are present in the MiniApp).
Now the problem is that git does not push empty directories, we noticed that with GitHub, but I guess it's true of all providers, must be in git itself. Therefore the empty directory will not be present in the git repository thus leading to the issue.
Will fix by creating a dummy README.md file inside the assets directory, just so that the directory will be properly pushed with git.
