### ISSUE TITLE
Guidance on data solution

### ISSUE THREAD

**Issue by devpascoe** [electrode-io/electrode-native#1095]
Apologies for posting here, I'm very new to Electrode and Electrode Native. I have a working sample of a cauldron, native app, 2x mini apps and a container.

Within each mini app i am using the Bridge to sendRequest and handle a response between MiniApps. So far all good.

I'm now looking at one of my traditional React Native projects and because that is heavy on redux i'm wondering how to approach a similar concept here.
I suppose I could have one miniapp being the source of truth for client data handling apis and locally saved redux props/data. Then use the Bridge mechanism to hand out data as requested by multiple other miniapps. Hmm not sure i'll get reactivity though since i can't pass down props.

I know there is the concept of an Api and ApiImpl however i want to keep everything private and feel that Api and Impl go overkill for what i want (a simple redux store accessible to other miniapps).

My intention is to componentize a pre-existing React Native app and i'm just after how to do things the electrode native way especially regarding a central data store. Note: i'm keen to have as little native code as possible, JS all the things.

Any insight is appreciated.

**Comment by devpascoe** [comment]
Bump 😎

**Comment by devpascoe** [comment]
Hey @jduthon reckon you could provide some insight? Thank you

**Comment by jduthon** [comment]
Hey @devpascoe,
I am only a `electrode-native` user and don't have much insights on achieving what you are looking for.
Though (and again I am not responsible for this repo, so those words are mine and mine only :) )I would recommend easing a bit the number of notifications you are going for here.

This project is open-source and delivered for free, and the core team seems to be relatively small. Commenting every single day on issues will not achieve much except create noise and annoy the very people you hope to be helped from (and from whom you have already received help as working software). So please be considerate on when to bump a thread.

**Comment by devpascoe** [comment]
Forgive my excitement/energy. Fresh to the framework. I figured being backed by Walmart Labs they’d jump on support to help uptake etc. plus there’s nothing on Stack overflow so unsure where else to ask these questions. 

But I’ll take what you said on board and suppress my need for wanting all the answers immediately. Again ... just excited and too keen as this framework ticks so many boxes for my needs. 👍

And cheers for the reminder to be a good citizen on open source projects 🤭

**Comment by belemaire** [comment]
@devpascoe @jduthon 
Sorry about delay, team was offsite for most of the week, I will take a look at all opened issues today.

**Comment by belemaire** [comment]
@devpascoe 
Working mostly on core Electrode Native platform and not on MiniApps development, I don't have top expertise to give clear guidance on this. That being said, being in relation with some internal app teams, I know that similar questions were raised and figured out in some way.

From what I know, sharing a single Redux store for all MiniApps was deemed too complex (or even not technically feasible, but I doubt that) and teams did not go down this road.

Also, having a single redux store, introduces at some level extra coupling between the MiniApps. The concept of having different repos / different teams, is at a design level done to reduce coupling between the different teams / MiniApps. 

At some point I remember that we mentioned to the teams that if two MiniApps are sharing a LOT of state, then it probably means that they probably should not be two MiniApps but just a single MiniApp ;) MiniApps are meant by design to be clearly isolated from each other.

Some state still needs to be shared globally, state that is more horizontal than vertical. For this you could use in some way a solution around AsyncStorage or some DB (if that state need to be persisted), or if it does not need to be persisted, you could just write a very simple key/value pair library that keeps some global state in an object and expose set/get methods given a key. All MiniApps can import this lib initialized as a singleton and this way can share some state.

Also we have a [navigation api](https://github.com/electrode-io/ern-navigation-api) that we are using internally and that our MiniApps are using to navigate between each other. It's not really documented (pretty new) but does not have a lot of methods, implementation needs to be done on your native side as well, but basically we use it because we have brownfield native apps were navigation bar is handled on the native side, we don't want any navigation bar rendered by react native. It's also used by MiniApps (or native app) to navigate to a different MiniApp, with the option to provide the MiniApp that it navigates to, some extra data (as a JSON payload ... passed as initialProps to the MiniApp being navigated to).

But in the end, to recap, our MiniApps are not sharing any pure Redux state. Each MiniApp maintain its own Redux store. State that is shared between MiniApps is minimal and mostly global state not having to do with the internal UI or data state of a specific MiniApp. To share this global state you can use AsyncStorage or just a dumb simple key/value pair singleton store. Also some MiniApps require some initial data to be started/navigated to, and we use our navigation API for this purpose. Going down the route of a single redux store might work, but it didn't for us for some reason (prob because we wanted cleared separation of concern/state).

Hope that give you some hints.

**Comment by devpascoe** [comment]
Oh wow cheers for the reply. So would the React Native AsyncStorage get value store work across miniapps?! That’ll work. 

Required is some saved important state across miniapps like user token or a profile id. 
More generic data cross miniapp might be downloaded and cached user profiles or posts etc. which sounds like I should consider downloading each time for each miniapp where there’s a logical separation. 

And I totally appreciate your point about separating out larger teams to focus on each miniapp.

**Comment by belemaire** [comment]
Yeah AsyncStorage will.
That being said, I wouldn't use AsyncStorage for data that does not need to be persisted (i.e kept even after app is killed), especially for sensitive data as AsyncStorage is not secured, if someone gets access to the phone physically, it can be accessed with some skill.
For non to be persisted data, but data that needs to be accessible as long as the mobile app is running I would just create a dumb simple JS lib (or reuse an existing one) that expose just some methods such as `get(key)` `set(key)` `has(key)`, something like that, which just store the key/values in a JS `store` object, or just expose the `store` JS object directly and let users use built-in JS methods to access key/values pairs. You can even build an extra more high level lib to offer more convenient methods to access know data such as `getUserProfile` if you don't want all miniapps to know that user profile is under the `USER_PROFILE` key ... up to you as far as you want to take it ;)
Then just export a singleton instance from that lib, so that when miniapps import the lib they get this singleton shared instance, thus accessing the same underlying store.

**Comment by belemaire** [comment]
Closing this one now, feel free to reopen if needed.
