### ISSUE TITLE
App.js getting re-render every time when we are changing the orientation of device 

### ISSUE THREAD

**Issue by ankit9495** [electrode-io/electrode-native#1120]
Hi @belemaire ,@gmbharath12

We have developed a mini app by using electrode native while we are changing the orientation of device, App.js get render every time. We do'nt want to re-render App.js every time.

The App.js code are mentioned below.

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View,Dimensions} from 'react-native';

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
export default class App extends Component<Props> {
  render() {
    console.log('Dimensions--------->');
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

We have tried at our end but not succeeded.Please let us know if you any solution.

Thanks

**Comment by ankit9495** [comment]
Hi @belemaire ,@gmbharath12
Is there any way to stop re-rendering of App.js every time while changing the orientation of the device?

I have change the AndroidManifest.xml to stop activity to re-create when we rotate the screen in MainActivity.

            android:configChanges="orientation|screenSize|keyboardHidden">

But still not working.
Can you please suggest any solution for that ?

Electrode native version : v0.31.2

Thanks

**Comment by belemaire** [comment]
Hi @ankit9495 

This "issue" is not really related to the use of Electrode Native, nor React Native but is due to the Android Activity lifecycle. Anytime the screen is rotated, Activity is recreated, which triggers re-renders of the app, that's the way it is with Android. Even with Fragments, the view attached to it will be destroyed and recreated to my understanding.

That is just the way Android works, independently of React Native so there is not much we can help with here, it is a purely applicative "issue" not an Electrode Native one.

You can check this article device orientation in React Native, and can find other ones online, but unless you go through some native hacks, I don't think there is a way to bypass the re-render on orientation change.  https://medium.com/react-native-training/build-responsive-react-native-views-for-any-device-and-support-orientation-change-1c8beba5bc23
