### ISSUE TITLE
[Feature] CodePush promote command should use the targetSemVerDescriptor as the release being promoted

### ISSUE THREAD

**Issue by LuisRizo** [electrode-io/electrode-native#1229]
Currently, the description of the release being promoted is being copied if the `ern code-push promote` command does not include it by default.

>--description/--des
Description of the changes made to the app with this release. If omitted, the description from the release being promoted will be used.

It would be very helpful if the same applied to the `targetSemVerDescriptor`

**Comment by belemaire** [comment]
Thanks @LuisRizo for the suggestion.
This makes sense. However we don't keep track of the `targetSemVerDescriptor` or `targetDescriptors` that were used when issuing the initial `release` command. To support this, we will need to keep this information in Cauldron, in the metadata associated to the code push release, so that we can reuse the one that was used for `release`, upon `promote`. This shouldn't be much, but we have to look more closely to it, to make sure it does not have any unwanted side effects and that we cover all edge cases.

**Comment by LuisRizo** [comment]
Hello @belemaire, thank you for the quick response. I actually suggested this because I noticed that my cauldron had both the description and the target binary version on the cauldron under the `appVersion` key.

Here is a code snippet from my generated cauldron on ern version `0.32.2`:

```
{
              "name": "7.6.0",
              "binary": null,
              "codePush": {
                "Staging": [
                  {
                    "metadata": {
                      "appVersion": "~7.6.0", // <-- This is the semantic version I used to deploy to Staging that I would like the `promote` command to pick up.
                      "deploymentName": "Staging",
                      "description": "Updated dependencies",
                      "isMandatory": true,
                      "label": "v100",
                      "releaseMethod": "Upload",
                      "rollout": 100,
                      "size": 910484
                    },
                    "miniapps": [
                      "git+ssh://git@github.com/org/miniapp-repo.git#some-commit-hash"
                    ],
                    "jsApiImpls": []
                  }
                ]
              },
			  ...
```

**Comment by belemaire** [comment]
Oh that's a good thing 👍 

Thanks for the info, wasn't remembering all the specifics when I wrote my initial comment.
So this should make things a bit easier. The only thing that remains is if the user used the `--descriptors` option of our `code-push release` command rather than `--semVerDescriptors`.

In that case, for example if `--descriptors myapp:android:1.0.0 myapp:android:2.0.0` is used, then the `appVersion` in the code push metadata kept in the Cauldron will be `1.0.0` (in the metadata entry of `myapp:android:1.0.0`) and `2.0.0` (in the metadata entry of `myapp:android:2.0.0`), thus losing the original information that it was a push for 2 different versions.

There are different ways around that I think. 
- We keep the `--descriptors` option and we add a new field to the code push metatada to contain all the descriptors used. But this is a bit bad as it's not really a real code push metadata entry, and it will make logic more complex.
- We keep the `--descriptors` option but we convert it on the fly to a semver range, so that internally we will use semver and it will reflect in `appVersion`. For previous example, electrode native would convert to a semver range such as `1.0.0|| 2.0.0'`. This way we just reuse `appVersion` that was used for release when we use promote. No special logic involved except for converting the `--descriptors` versions to a semver range (easy enough).
- We remove the `--descriptors` option all together and only keep the `--semVerDescriptor` one. This would be a breaking change and would force user to provide semver descriptor in any case.

Given that option 2 is easy enough to implement and does not introduce any breaking changes, we will probably just go with this one. We will look into it.

**Comment by LuisRizo** [comment]
Would using the `targetBinaryVersion` flag n the `ern code-push release` command take priority over the generated semver when using two descriptors?

I always use the `-d` flag but only have a single app. On top of that I use the `targetBinaryVersion` and this is the value that I would like the `ern code-push promote` command to pick up automatically.

Does that sound like what you had in mind?
