### ISSUE TITLE
Fonts are not copied from npm package

### ISSUE THREAD

**Issue by romanlv** [electrode-io/electrode-native#1348]
we have `rn-shared-components` package with custom fonts in `/assets/fonts` folder 
in package.json it has 
```
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  },
```

which works just fine for development, fonts are are applied for ios and android ErnRunners 

but when android container is generated those fonts are missing in `/lib/src/main/assets/fonts` folder 

I had to update android build script to include this line 
```
cp -f $CONT/lib/src/main/rn-shared-components/assets/fonts/*.ttf $CONT/lib/src/main/assets/fonts
``` 
which is not a big deal, but it's clearly something that should happen inside `ern create-container  -p=android ...`

**Comment by romanlv** [comment]
`ern --version`

```
ℹ ern-local-cli : 0.37.8
ℹ electrode-native : 1.0.17
```

**Comment by belemaire** [comment]
Hi @romanlv 

Electrode Native only support `rnpm` directives that are declared by MiniApps, not of any direct or transitive dependencies of MiniApps (otherwise it would have to parse the `package.json` of all the packages in `node_modules` to find if they contain `rnpm` directives which would be too costly). 

That being said, `rnpm` is anyway now being deprecated by React Native in favor of new `react-native.config.js` way, and Electrode Native does support fonts assets declared through`react-native.config.js` even in direct/transitive dependencies of MiniApps (starting from Electrode Native 0.37.5).

I think you are referring to our internal react native shared components library. If that's the case, starting from version `7.0.6` of this lib, a `react-native.config.js` has been added to it. We have tested the setup and it should properly copy fonts to container for both iOS / Android.

If for some reason you cannot update Electrode Native to a version >= 0.37.5 and/or shared lib to a version >= 7.0.6 then you will have to keep manual way. Otherwise it should be handled properly, let us know otherwise.

**Comment by romanlv** [comment]
@belemaire 
Thanks for the reply.
 
I checked the code, we actually have 

```
  "rnpm": {
    "assets": [
      "../rn-shared-components/assets/fonts/"
    ]
  }
```
in the apps `package.json`, that's how it was able to work on ios i think. 

As for `react-native.config.js`, I was testing it with the latest `ern@0.38.4` and it seems to be affecting both platforms now. 

This is the behavior I'm experiencing: 
- in development, `ern run-ios` creates project without linked fonts
- running `react-native link` fixes the problem, but only when `react-native.cofig.js` is present in the app itself, not in `shared-components` library
- running release build with published apps `ern run-ios --miniapps ...` creates app without custom fonts on both platforms
- creating container, custom fonts are missing from the output, `./ElectrodeContainer/Libraries/MiniApp/assets/node_modules/@walmartca/rn-shared-components/assets/fonts` is included, but it only contains .json file (glyphs mapping)

With mentioned issues we cannot start using `0.38.x`
