### ISSUE TITLE
Adding an API to the cauldron results in an error

### ISSUE THREAD

**Issue by LcTwisk** [electrode-io/electrode-native#1423]
I'm trying to add a generated API (pushed to a git repo) to the cauldron. It looks like ern is trying to find it in the npm repo.

Steps to reproduce:
1) Create a new API using `ern create-api`
2) Push the API to a repository on GitHub
3) Add the API to the cauldron using:
`ern cauldron add jsapiimpls 'git@github.com:LcTwisk/example-api.git#master'`

Result:
```
✔ Connecting to the Cauldron 3s
✔ Connecting to the Cauldron 3s
✔ Ensuring that native application descriptor exists in Cauldron 0s
✔ Connecting to the Cauldron 3s
✔ Ensuring that native application descriptor exists in Cauldron 0s
✔ Ensuring that version is fixed 0s
✔ Generating Composite from Cauldron 26s
  ✔ Generating Composite 25s
    ✔ Cleaning up existing composite directory 0s
    ✔ [1/2] Adding git+ssh://git@github.com/LcTwisk/example-miniapp.git#8f3e8c411db52bbf070edb9cde7e7a162ea28a5f 15s
    ✔ [2/2] Adding git+ssh://git@github.com/LcTwisk/example-api.git#48a5163d27e337f56c546fc909161d1260318156 5s
  ✔ Syncing https://github.com/electrode-io/electrode-native-manifest.git Manifest 1s
✖ [syncCauldronContainer] An error occurred: Error: Could not find example-api package
✖ An error occurred: Could not find example-api package
```

I haven't tried publishing the API to npm, for my MiniApp I didn't face any problems hosting it on GitHub.
Any help would be appreciated :)

**Comment by belemaire** [comment]
Hey @LcTwisk 
Will have a closer look to the error and try to improve error message.

That being said, APIs shouldn't be added to a cauldron. Only JS API implementations should be (and still, we might remove this as it's the cause of some confusion and does not add much value). So to put it in a nutshell, only miniapps should be added to the Cauldron.

When you create an API you should publish it to npm as we unfortunately don't yet support including APIs from git (if you don't want to publish to npm, you can easily setup a tool such as [verdaccio](https://github.com/verdaccio/verdaccio) which will let you publish npm package to a local registry running on your machine).

Then you should just add a dependency to the API in the MiniApp(s) that are going to use it.
But an API without an implementation is of no use (for example if your API expose a request `getMovies`, there should be some code somewhere that implements this functionality and return the movies). 

You can implement the API either as a native implementation (Swift/Java) or as a JavaScript implementation. That being said, JavaScript implementation only makes sense if the native application needs to consume your API, otherwise you shouldn't bother with APIs and can just create JS libraries.

If you want to implement the API natively, there are two different approaches :

- Create a standalone API implementation project (using `create-api-impl` command) and publish it to npm (or verdaccio during testing). This is the most easiest road in most cases. It'll generate an API implementation skeleton project based on your API and you'll just have to fill in the gaps (i.e implement the API request handlers). Then you can just import the api implementation package in your MiniApp.
- Directly implement the API in the native application. This is the less favored road as it tightly couples the API implementation to the native application and make it hard to redistribute / test in isolation, but sometimes this is the easiest way (if working with a large existing native application and need to get access to things from the native app that are not easily extractable to make them standalone).

Hope it clarifies things a bit.

**Comment by LcTwisk** [comment]
Hey @belemaire
Thank you so much for your explanation. 
I'm now using just the API, without implementation, to delegate back from React-Native to Native. Similar to the color picker app in this example: https://github.com/electrode-io/electrode-native-showcaseapp-ios.
Or do you have a better way to organise this delegation from RN->Native?
Thanks!
