### ISSUE TITLE
Support React Native 0.61.x

### ISSUE THREAD

**Issue by LcTwisk** [electrode-io/electrode-native#1446]
Hello!

Are there any plans to support React Native 0.61.x in the near future? If not, what would be the steps to get started into adding the support myself?
The new React Native version will make it easier to distribute a container using Cocoapods, something I'm really looking forward to.

**Comment by friederbluemle** [comment]
Hi @LcTwisk - Thanks for your question. We are actively looking into adding support for RN 0.61+. Due to the changes to the way dependencies are declared on the iOS part (related to CocoaPods), additional work on our end is required to make it work for all use cases. Expect an update soon, we'll keep this issue open and reference it accordingly. Thank you.

**Comment by julasamer** [comment]
I am also curious about the status of this feature. Do you have any new information if/when RN 0.61 will be supported?

**Comment by belemaire** [comment]
Closed by https://github.com/electrode-io/electrode-native/pull/1542
