### ISSUE TITLE
Hangs on "Waiting for device to start" on `ern run-android`

### ISSUE THREAD

**Issue by AndrewSouthpaw** [electrode-io/electrode-native#1489]
Repro

1. Without an Android simulator open, run `ern run-android` on MiniApp
1. Eventually it'll hang, prompting "Waiting for device to start"

For beginners, this line is not obvious: it wants the user to take action, going to Android Studio and turning on the Android simulator through the AVD. If it's not possible to programmatically launch an Android simulator, it would be nice to at least update the text.

I searched for the string across GitHub and didn't find where the logic is living, but if you want to point me to where the CLI prompts this I'd be happy to offer some copy in a PR.

**Comment by friederbluemle** [comment]
I _think_ this issue is about the case where _no_ avds (Android Virtual Devices, i.e. emulators) are _configured_ on the host machine.

I'm not able to repro this as stated in the issue description, at least with the latest version of ERN, and I don't think much has changed for several versions.

- **with** emulators configured (i.e. non-empty `~/.android/avd`)

  ```
  $ ern run-android
  ...

  ? Choose Android device image
  ❯ Nexus_5X_API_29_x86
    Pixel_2_API_21
    Pixel_3_API_29
    Polestar_2_API_28
  ```

- **without** emulators configured (i.e. empty `~/.android/avd`)

  ```
  $ ern run-android
  ...

  ? Choose Android device image (Use arrow keys)
  ❯
  ```

In both cases it is waiting for input. A problem occurs in the second case (empty list), _after_ selecting the empty entry. And yes, that's definitely something ERN should handle better. Instead of displaying an empty list and then waiting indefinitely, how about a simple error message that makes it clear that it's not possible to run an Android app:

```
Unable to launch app: No devices connected and no emulators configured.
```

An emulator is set up _by default_ during the installation of Android Studio/the Android SDK (which is already a requirement of ERN).

**Comment by friederbluemle** [comment]
I just checked how React Native handles the situation, and it's similar to what I suggested above:

```
$ yarn android
...
info Launching emulator...
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
warn Please launch an emulator manually or connect a device. Otherwise app may fail to launch.

[building app]

error Failed to install the app. Make sure you have an Android emulator running or a device connected. Run CLI with --verbose flag for more details.
```

**Comment by krunalsshah** [comment]
resolved https://github.com/electrode-io/electrode-native/pull/1628
