### ISSUE TITLE
CodePush --disableDuplicateReleaseError flag not working

### ISSUE THREAD

**Issue by LuisRizo** [electrode-io/electrode-native#1596]
Hey there. First of all, thank you for adding support for the `--disableDuplicateReleaseError` flag. If memory serves me right, I remember that in a previous SDK version it was working great.

However, now that I'm using ern version 0.40.4, it seems to have stopped working.

It does make a difference based on the output that I'm getting from the `ern code-push release` command, but I don't see a new CodePush being released on AppCenter.

Here's the output when not using the `--disableDuplicateReleaseError` flag after trying to release a new CodePush with no JavaScript changes:

```
✔ Generating composite bundle for miniapps 1m 18s
✔ Connecting to the Cauldron 0s
ℹ Target Binary version : 7.19.x
✖ Releasing bundle through CodePush 5s
✖ performCodePushOtaUpdate {e}
✖ An error occurred: [object Object]
```

and this is the output when using the flag:

```
✔ Generating composite bundle for miniapps 1m 33s
✔ Connecting to the Cauldron 0s
ℹ Target Binary version : 7.19.x
✔ Releasing bundle through CodePush 7s
  ⚠ The uploaded package was not released because it is identical to the contents of the specified deployment's current release.
ℹ Successfully released
```

As you can also notice, the first error log is not very helpful, but that's a separate issue. The fact is that it actually fails the command when the flag is not provided. But when it is, it appears that the command is not being forwarded to CodePush and thus a new CodePush is *not* generated.

Ideally, at least in my opinion, I should be able to send a new CodePush to AppCenter even if the code is the same when I provide that flag.

**Comment by belemaire** [comment]
Hi @LuisRizo,

The separate issue regarding unhelpful error log has been addressed by https://github.com/electrode-io/electrode-native/pull/1570. Will be part of next release.

Regarding the `--disableDuplicateReleaseError` flag, the behavior experienced is the correct one.
Only problem I see here is the last info message stating `Successfully released` when nothing was actually really released. We will get rid of this one to avoid confusion.

The "problem" is actually on the CodePush server (AppCenter) so there is not much we can do here on our end. The server will reject any bundle targeting a version if the bundle currently stored in the server for this version is exactly identical to the one you are trying to push. This makes sense as there is no real point in creating a new entry / label on the server side for a bundle that is the exact same one as previous one.

When the server send us back such a response, saying that the bundle is the same as the current one, the default behavior on the CLI side is to exit the process with an error (same behavior with code-push official cli), a [similar flag was introduced on the code-push appcenter CLI](https://github.com/microsoft/code-push/pull/324). What this flag does is just to consider such a duplicate bundle response coming from the server, as a warning instead of an error, and thus not exiting the process.

**Comment by LuisRizo** [comment]
Oh right. Sorry I apologize, it's been a minute since I last looked into the real meaning of `--disableDuplicateReleaseError`.

I guess the main reason I was expecting the command above to run even on a CodePush with no changes was so that I could update the mobile-clinical-cauldron.

Let me explain what happened:

The native app is already on version 7.19.0, but I was having issues deploying to CodePush because of the regression caused on `ern` 0.40.0 (https://github.com/electrode-io/electrode-native/pull/1536). So since I didn't have much time to look into the issue, I decided to deploy the CodePush using an older `descriptor`, but with the `--targetBinaryVersion` of 7.19.0.

Now once I figured out what the issue was and upgraded my `ern` CLI to latest, I was hoping to run the same command just to update the cauldron so that the version 7.19.0 was up to date and showed a CodePush released to it.

Since now I understand the reason for the `disableDuplicateReleaseError`, I can close the issue. But I'd like to hear from you as to how would you suggest I update the cauldron for a CodePush that was already released
