### ISSUE TITLE
TypeError: Cannot read property 'getDevices' of undefined

### ISSUE THREAD

**Issue by briviere** [electrode-io/electrode-native#188]
I was trying to go through the MovieListMiniApp tutorial but I'm getting the following error message: 

```
| __| |___ __| |_ _ _ ___  __| |___  | \| |__ _| |_(_)_ _____ 
| _|| / -_) _|  _| '_/ _ \/ _` / -_) | .` / _` |  _| \ V / -_)
|___|_\___\__|\__|_| \___/\__,_\___| |_|\_\__,_|\__|_|\_/\___|
[v1000.0.0] [Cauldron: -NONE-]

A React Native Packager is already running in a different process
✔ Preparing MiniApp(s) and running compatibility checks
✔ Creating local Container
✔ Regenerating iOS Runner Configuration
TypeError: Cannot read property 'getDevices' of undefined
```

**Comment by belemaire** [comment]
@briviere I can see you are using the development version of Electrode Native (1000.0.0). We had a similar issue recently using the development version. This issue was fixed and not present in released (non-dev) versions of Electrode Native.

From your local clone of `electrode-native` project, please pull (or merge/rebase if you are on a branch) the latest from our master.

Also, you should run `npm run rebuild` from the root of `electrode-native` every time you get the latest from master (or anytime you add a new package dependency to one of the `ern-` module in the project). 

I will add instructions on this in our CONTRIBUTING page regarding, as its missing. But basically what this does is make sure that all new dependencies added to some `ern-` module are installed properly (doing that through lerna).

**Comment by briviere** [comment]
I was able to get the MiniApp running by using the v0.8 branch and running nom run rebuild.
