### ISSUE TITLE
Can't find non-simulator iPhone in list of devices

### ISSUE THREAD

**Issue by amloelxer** [electrode-io/electrode-native#223]
When running `ern run-ios` from the command line, I'm presented with a list of simulator devices to run my Mini app on and my actual device never appears. Is there anything I need to do in particular to run on an actual phone? I would run from the Ern Runner Xcode project itself, but when building, I get a list of errors. Thanks in advance!

**Comment by belemaire** [comment]
@amloelxer 
Thanks for reporting this.

Actually, while `run-android` command supports for launching the runner on a connected device, `run-ios` only supports run on a simulator, not a connected device.

This is actually not a bug, but a missing feature of the `run-ios` command.

I classified this issue as `Command Improvement`, we will look into it as soon as possible to make `run` command experience on parity with Android.

That being said, you shouldn't get errors when trying to build the generated Runner project directly from XCode. Maybe just try to launch it on a simulator first (through `run-ios`) and if that works, try opening the project in XCode and launching it from there (maybe we do some processing on the generated Runner project after a simulator is selected, so generation might not be complete if you don't pick a simulator first ... not sure though, and it would be a bug).

If you still face issue trying to launch it directly from XCode, please open a separate issue for this. We'll keep this current issue for the `run-ios` command improvement (to add support to launch on connected device instead of simulator for `run-ios`).

Thanks !

**Comment by amloelxer** [comment]
@belemaire thanks so much for the response and detail! I'll open up a separate issue.
