### ISSUE TITLE
introduce -exact flag in the create-api command 

### ISSUE THREAD

**Issue by krunalsshah** [electrode-io/electrode-native#287]
currently the `create-api` appends `react-native-.+-api` to the apiName. instead it would be nicer to have to `exact` flag
Problem : `ern create-api my-api` results in `react-native-my-api-api`
Enhancement : using exact flag it could just be generated as package `my-api`

@belemaire @deepueg thoughts?

**Comment by belemaire** [comment]
@krunalsshah 

The API name provided by the user to `create-api` command should be the name that is used (and added in the `ern` package.json object as `moduleName`). This is the same experience as `create-miniapp`.

The problem I see here and that we discussed, is that if I specify the name `WeatherApi`, then the prompted package name suggestion will be `weather-api-api` which is ... bad.

That being said, this is the right name ... because it's more intuitive and looks better to call in Android or iOS or JS `WeatherApi.requests. ...` rather than `Weather.requests. ...`.

Two things I would suggest here :

1) If the module name that the user provide to command, is not suffixed by Api, suggest the user to suffix the Api through a prompt.

i.e, something like

```console
$ ern create-api Weather
> To follow naming conventions we suggest suffixing the name of your API with Api
> Do you want to name the Api as WeatherApi rather than Weather ? Y/n
```

If the module name provided by the user is already suffixed by `Api`, then do not prompt.

2) If the module name that the user provide (or modified by prompt) is suffixed by Api, do not add `-api` suffix for package name to avoid `-api-api` crap.


Does it makes sense ?

**Comment by belemaire** [comment]
@krunalsshah 

BTW for point 2. the same should be applied for `create-miniapp` and `create-api-impl`

Just re-did the Getting Started guide and when I ran `ern create-miniapp MovieListMiniApp` it propose a package name as : `movie-list-mini-app-miniapp` :(

So let's make point 2. a specific issue.

We should create an issue for point 2. (`Do not add module suffix in name if already present`) covering `create-miniapp`, `create-api` and `create-api-impl` and create another issue for point 1. covering `create-miniapp`, `create-api` and `create-api-impl` as well.

**Comment by krunalsshah** [comment]
@belemaire thanks 
Issues created 
https://github.com/electrode-io/electrode-native/issues/315
https://github.com/electrode-io/electrode-native/issues/316
