### ISSUE TITLE
code-push command should support semver range

### ISSUE THREAD

**Issue by belemaire** [electrode-io/electrode-native#303]
`code-push` command should accept a semver to target one or more versions (as Microsoft `code-push` command already offers). 

We should apply the same exact rules as the Microsoft `code-push` (considering `ern` ultimately forwards the command to Microsoft `code-push` client for execution).

If the semver used is a range that targets multiple version, `ern` should properly perform multiple `code-push` updates for each matching version and update the Cauldron accordingly.

**Comment by devpascoe** [comment]
Following up on this one i noticed if i specify ern code-push release --targetBinaryVersion ^1.0 i get the target version under app center displaying the correct ^1.0 value.
But if i specify ern code-push release --targetBinaryVersion * i am unable to build in order to release. So it looks like the * wildcard does not work.
