### ISSUE TITLE
Application MovieDetailsMiniApp has not been registered

### ISSUE THREAD

**Issue by kushan85** [electrode-io/electrode-native#400]
On following the getting started electrode native page
https://electrode.gitbooks.io/electrode-native/getting-started/getting-started.html

Getting this error when clicking on the list to navigate to the details page. Tried the hint in the error but still getting the error.

Application MovieDetailsMiniApp has not been registered.

Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before.
If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into app folder and run 'npm start').

This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.

runApplication
    AppRegistry.js:191:6
__callFunction
    MessageQueue.js:302:47
<unknown>
    MessageQueue.js:116:26
__guard
    MessageQueue.js:265:6
callFunctionReturnFlushedQueue
    MessageQueue.js:115:17

**Comment by krunalsshah** [comment]
Thanks for writing to us. 

There are few reasons why this error can occur
- If name of the project doesn't match the registered component . Check if <appName> used for running `ern create-miniapp <appName>` matches `AppRegistry.registerComponent( '<appName>', () => AnyName );` in `index.js` file. Likely not the problem with the issue you reported
- If npm packager is running in a terminal started for a MiniApp that is different from the one you are navigating to. Likely the issue you are facing. For example `MovieListMiniApp` & `MovieDetailsMiniApp` are 2 different miniapps. Let's say your npm packager was started for `MovieListMiniApp` & you click on a movie. This operation will fail as packager would have only packaged `MovieListMiniApp` in the bundle , so App discovery from the registry would fail.

So most of what you have explained is the expected behavior and the application under test must have the packager running to avoid the error above. Please reach out if you would like to know more. Thanks. 

Resolution: No action required.

**Comment by cohen72** [comment]
@kushan85 according to the docs:

> To add this MiniApp to the local container used by the native application, use a variation of the ern run command that allows you to include extra MiniApps to the local Container. Let's do that magic now.  
> ```
> $ cd MovieListMiniApp //make sure you are in root dir of MovieListMiniApp
> $ ern run-ios --miniapps moviedetailsminiapp@0.0.20 --mainMiniAppName MovieListMiniApp
> ```
