### ISSUE TITLE
Process is stuck while creating container locally

### ISSUE THREAD

**Issue by Jupneet** [electrode-io/electrode-native#404]
After passing the validity checks and selecting an app, the process is stuck at creating local container from Claudron. Not getting any error. It keeps loading with message "Creating Container for myapp:android:0.0.1 from Cauldron"

**Comment by belemaire** [comment]
You should retry with trace logs enabled for the command.
You can do that by prefixing the command with `ERN_LOG_LEVEL=trace`. For example, `ERN_LOG_LEVEL=debug create-container ...`.
A common reason for the `create-container` command to get stuck is that it cannot find in the npm registry one of the native dependency version or one of the miniapp version to be shipped in the Container.
This is because yarn is prompting the user to select a different version, but Electrode Native does not display the prompt, nor process stdin. This should not happen in the first place, all versions should have properly been published to NPM, so we should log an informative error message instead and abort container generation
Proper root issue opened here https://github.com/electrode-io/electrode-native/issues/412, will be shipped in next Electrode Native version.
Thanks for reporting.

**Comment by belemaire** [comment]
Closing this one, will ping back on it once #412 is closed.
