### ISSUE TITLE
TypeScript integration?

### ISSUE THREAD

**Issue by abdyer** [electrode-io/electrode-native#405]
We have some existing React Native components written in TypeScript that we would like to migrate to an Electrode Native MiniApp. After searching the source code for how we might specify an alternate entry file path, I found [a couple places](https://github.com/electrode-io/electrode-native/search?utf8=%E2%9C%93&q=entryfile&type=) where this could be done, but I'm not quite sure how to integrate the `tsc` compile command or whether changing the entry file is currently supported.

Does anyone have suggestions for getting TypeScript working in a MiniApp? Any background on the bundling process would be greatly appreciated. If it's not currently supported, I'm happy to make a pull request once I know how things currently work.

**Comment by abdyer** [comment]
This was much easier than I expected thanks to [react-native-typescript-transformer](https://github.com/ds300/react-native-typescript-transformer). See the README in the repo and [this blog post](http://blog.novanet.no/easy-typescript-with-react-native/) for everything you need to get this working with Electrode Native.

**Comment by Igor1201** [comment]
Hey @abdyer, I'm currently trying to used typescript on a miniapp and it's fine to develop (because I can have a `rn-cli.config.js` file specifying the transformer, project root and source exts).

However, when I try to update this typescript miniapp on my cauldron, it won't compile due to the fact the composite application `ern-container-gen` generates doesn't have a `rn-cli.config.js` file configured for a single miniapp.

Did you have the same issue?
