### ISSUE TITLE
NPM dependencies containing native code must be prefixed with 'react-native-' in order for Manifest config to be processed

### ISSUE THREAD

**Issue by abdyer** [electrode-io/electrode-native#428]
When specifying the Manifest config/plugins for [AppCenter](https://github.com/Microsoft/AppCenter-SDK-React-Native), it took me awhile to realize that it was being ignored because the various AppCenter dependencies (`appcenter`, `appcenter-analytics`, `appcenter-tracking`) do not start with `react-native-` ([source code here](https://github.com/electrode-io/electrode-native/blob/0928a6dccc93aac099085ae5ac7976662baf0c40/ern-util/src/findNativeDependencies.js#L24)). The ugly workaround is to simply publish these to an internal NPM registry with the expected prefix, but a cleaner way to do this would be greatly appreciated.

Even still, this is a minor concession for using such a great platform for integrating React Native. Thanks again for the great work!

**Comment by belemaire** [comment]
Thanks @abdyer for the feedback !

Actually, we just ran into a similar issue yesterday when someone internal created an Electrode Native API which package name was not prefixed with `react-native`. It was leading to the API not being injected in the Container during generation, because of the exact same line of code you are pointing to.

We're going a different road for this one though as we will impose the convention for API naming to follow `react-native-[API_NAME]-api`. This will be enforced by the `create-api` commands.

Prefixing react native modules that contain native code with `react-native` is a convention that is widely adopted, and for our APIs we want to enforce it as well (as well as the -api suffix) so that we can easily identify api modules just by looking at their name.

Unfortunately, we cannot control third party native modules naming and cannot expect that they will follow the react native common naming convention. As you can see in the code however, we just assume that the convention is followed. It was not creating any issue on our side and we forgot a bit about this line of code, as all the third party native modules that we are using internally up until now are all properly following the naming convention.

Historically, the problem we faced at one point (and the reason why we added this prefix check) was that a team was using a JS dependency in their MiniApp that was containing some native code inside (maybe appium/selenium testing tools). Because it was containing some native code, the `findNativeDependencies` lookup algorithm was flagging it as a native module and was then failing Container generation because no configuration was found for it in the Manifest on how to inject it in the Container. But it was a false positive because it was not a react native native module and we didn't want to inject this native code in the Container ... so we took the easy path at this time of assuming that native modules are starting with `react-native` prefix, fixing this issue.

The simplicity of this approach is biting as us now, as you just experienced ;)

Given that EN will control/enforce Electrode Native APIs naming, the lookup algorithm will be pretty simple to find them during container generation. The problem is for third party native modules. It is going to be hard to update the lookup algorithm for it to properly filter out all possible false positives. In the end, at an high level, what the lookup algorithm is used for is just to find all node modules that contain native code, and if its not an API or APIImpl, look in the manifest to see if there is an injection configuration for the module, and if not abort container generation with an error. 

What we could do instead is keep a similar algorithm (minus the `react-native` prefix filtering), and if we detect any third party modules that do not have a configuration in the manifest, just log a warning instead of aborting container generation. The disadvantage is that if that is legit .. let's say `appcenter-analytics` is detected which is really a native module, and it does not have any injection configuration declared in the Manifest, we will log a warning but the user might not pay attention to it and end up with a generated Container that does not include the code of the native module. That being said I don't see better alternatives, unless we have a lookup algorithm that works 100% with no false positives (not sure it's possible) or if we keep the current lookup algorithm (minus `react-native` prefix filtering) and the user should maintain (or maintained in the public master manifest) a list of false positives so that platform would just skip them and still fail container generation early.

I think we will go with the warning way at this point. If we notice some users opening issue to complain that the container is not containing the third party native module they are using in their MiniApp(s), it's probably that they did not pay attention to the warning during container generation, in which case we might rethink the approach and go for a false positive exclusion list maintained in the master manifest.

I will create a proper issue for the implementation (removing `react-native` filter prefix and logging a warning instead of erroring if a module containing native code is detected and do not have any associated configuration in the manifest). This is not a big task so we will ship it in next release (0.11.0) which should be available before the end of this week.

**Comment by belemaire** [comment]
Opened https://github.com/electrode-io/electrode-native/issues/430

**Comment by abdyer** [comment]
Thanks for taking the time to explain the rationale for the current behavior. I think logging a warning when configuration is missing for a third party module is a good way to handle this. Doing so makes the situation easy to understand when a dependency does not show up in the container. The converse (ignoring configurations for dependencies that don't start with `react-native-`) was a lot harder to troubleshoot.

Great to hear you expect to have the fix out so quickly!

**Comment by belemaire** [comment]
@abdyer FYI we have just release Electrode Native 0.11.0 that include the fix. 
`appcenter`, `appcenter-analytics` and `appcenter-tracking` should therefore now be properly recognized as native plugins. as all third party native modules, they still need a proper configuration in the Manifest (public or overridden one) to be injected in the Container during generation.
If you come up with working plugin injection configurations for these plugins, even on a single platform, please consider contributing back the plugin injection config to the master manifest :)
