### ISSUE TITLE
ern create-container "--platform" argument is ignored

### ISSUE THREAD

**Issue by jomnius** [electrode-io/electrode-native#556]
During ERN version 0.11.x it was possible to create container from command line e.g.

```
ern create-container --platform android --version 1.0.2
ern create-container --platform ios --version 1.0.2
```
The --version option was broken, so the command actually didn't do anything... but it was fixed. The fix seems to be REMOVAL of possibility to define app version number from command line.

The other --platform option is still listed in ern 0.12.1 help, but seems to be ignored. There is command line list asking to select both app platform and version:

> jmiettunen@mac my-miniapp (master) $ ern create-container --platform ios
[v0.12.1] [Cauldron: mfs-electrode-native-cauldron]
✔ Validity checks have passed
? Choose a non released native application version for which to generate container (Use arrow keys)
❯ mFSReactNative:android:1.0.2 
  mFSReactNative:ios:1.0.2 

**PROBLEM**: how would you automate a clean CI/CD build of ern application, if mandatory parameters cannot be set from command line?

**Possible fixes:**
- Remove also "--platform" option, since it doesn't do anything
- Replace previous "--version" with e.g. "--appversion" option
- Create another way to define parameters from command line

**Comment by belemaire** [comment]
Hi @jomnius,
A few things :
- `--platform` option is useful if you don't generate a Container from a Cauldron. Indeed, when you are generating a Container from a Cauldron, the platform does not need to be specified as it is present in the Cauldron descriptor of the Native application version you are generating a Container for (for example if you create a Container for `mFSReactNative:android:1.0.2`, Electrode Native knows that the platform is android).
But `create-container` can be used to create Container not from a Cauldron but by directly providing to the command the MiniApps to be included in the Container (through `--miniapps` otpion). In that use case, Electrode Native has no way of knowing which platform to target (and we need to know the platform to create the react-native bundle targeting the right platform). So only in this use case the `--platform` option is useful. It is just ignored when creating a Container from a Cauldron. Hope this clarifies things (might update the command documentation to clarify things).
- If you want to create a Container from a Cauldron by setting all parameters on the command line (non interactive), in your case you can use the `--descriptor` option of `create-container`. For example if you want to create a Container for `mFSReactNative:android:1.0.2` then just use `create-container --descriptor mFSReactNative:android:1.0.2`. Once again, you don't need to use the platform option as the platform is part of the descriptor anyway.
- The `--version` option is gone from the `create-container` command due to the fact that version of the Container is only needed for publication of the Container (to a git repo and/or a Maven repo). Since `0.12.0` Container creation and Container publication are completely uncoupled. Therefore, if you are creating a Container using `create-container` command, you'll need to chain with `publish-container` command (which has a `--version` mandatory option). That being said, this is probably not what you want (not sure). The `create-container` / `publish-container` are used to create a local container and publish it, not really updating the Cauldron in any way (we are making use of it for our CI, we are currently in the process of finalizing our CI process, we will add some documentation arround it once we're done which might help other users to roll out their own). If your goal is to trigger generation and publication of a Container from a Cauldron (for ex `mFSReactNative:android:1.0.2`), then you can use the command (`ern cauldron regen-container --descriptor mFSReactNative:android:1.0.2`). What this command will do is regenerate the Container for this application version, and if any Container publishers are configured in the Cauldron for this native application, it will publish the newly regenerated Container using these publishers and will properly update the version of the Container in the Cauldron. By default it patch bumps the version of the Container, but `regen-container` accept an option `-v` to specify a custom version for the newly generated Container.

I hop this clarifies some of your concerns. Given the flexibility of Electrode Native there are different ways to achieve one thing and it might be confusing. If you need more help regarding the specific worfkflow you are trying to achieve, please let us know.

**Comment by jomnius** [comment]
Thank you, this was exactly what I was trying to do: clean CI/CD build from repos using ErnRunner app to contain our miniApp, to be released to HockeyApp. Now I am able to create the container from a script...

...which brings us to the next stop. I'll write a separate issue, trying to explain the problem with details. This issue can be closed.

Would be great, if you could update the docs (or write a blog post) about how to use ern create-container. Even now after your explanation, the solution is not obvious - when reading only the docs :)
