### ISSUE TITLE
How do I specify a Maven local publisher with ERN v0.12.2?

### ISSUE THREAD

**Issue by abdyer** [electrode-io/electrode-native#561]
Unfortunately, upgrading to ERN v0.12.2 did not get the `create-container` command working for me. It still behaves the same way described in #529.

Luckily, the new `publish-container` command is working with the same relative file `url`:

```
ern publish-container ~/.ern/containergen/out/android/ --version 1.0.0
--publisher maven --url file:~/.m2/repository
--config '{"artifactId":"some-ern-container","groupId":"com.walmartlabs.ern"}'
```

**Comment by belemaire** [comment]
Hi,

Container generation v.s publication are now completely separated.
- `create-container` command generates a container locally but does not handle publication and does not contain any specific publication directives in the generated code/config files.
- `publish-container` takes the path of a locally generated container and allow to publish it to git or maven (local or remote).

We don't want to rollback to the previous behavior of `create-container` publishing to Maven Local for Android as it would defy the purpose of clear separation of concerns between the two commands. Moreover, if we were to make an exception, the problem would be first explaining it (i.e `create-container` generates a local container and for Android it also publish it to Maven Local, if you need to publish it someplace else use `publish-container` -a bit confusing-), but the problem would also be that Maven publisher actually builds the Container (to generate the AAR to publish). What about if someone just want to generate the Android container and publish the resulting code to Git directly ((maybe to use as a submodule) rather than relying on an AAR. Maybe the box is a CI system that do not have android SDK and build tools installed (so no way to build the Container). We don't want to force user to install SDK and build tools if they don't plan on publishing to Maven (even local). So in that case we would have to introduce an additional flag to `create-container` to disable auto local maven publication (like `--noMavenLocalPublication`). That starts to look really messy.

We understand the convenience that was offered by `create-container` with automatic local maven publication for Android. We had some feedback (including yours) regarding this 'feature' disappearance. 
We discussed this internally, and as a compromise we decided that we will keep both command separated, but for `publish-container` we will provide defaults for maven publisher that are similar to what we used for local maven publication with `create-container` before the changes.

i.e, here will be the default values of `publish-container` when using `maven`publisher :
- url : `file:~/.m2/repository`
- artifactId: `local-ern-container`
- groupId: `com.walmarbs.ern`

This way will make it a bit simpler. Won't be as straightforward as `create-container` before, but still you'll just have to chain the two commands to achieve the same result as before (at the cost of a bit more verbosity).

`ern create-container --out ~/Code/MyContainer/android -p android && ern publish-container ~/Code/MyContainer/android --publisher maven`

**Comment by belemaire** [comment]
We will make this one out in next release of Electrode Native (scheduled for today, but we are a bit behind so might be Tuesday or Wednesday) 
Tracked by https://github.com/electrode-io/electrode-native/issues/562

**Comment by belemaire** [comment]
We will make the path optional as well (default is `~/.ern/containergen/out/[platform]`, to make chaining even less verbose :

```
ern create-container -p android --miniapps MyMiniApp@1.0.0 && publish-container --publisher maven
```

**Comment by abdyer** [comment]
Thanks for explaining. This does seem more flexible.
