### ISSUE TITLE
How to create Cauldron

### ISSUE THREAD

**Issue by kamleshgit** [electrode-io/electrode-native#581]
I have created two mini apps using electrode native and  am able to run them without issues which is good. Now my next target is to get these mini app integrated with my Android Native App. I read the documentation but not able to understand how to create Cauldron and then use it. Can some one please help me understanding the Cauldron concept and guide me on the detailed process of create a Cauldron and then use it?

My ultimate target is to integrate mini apps with my existing native app.

Please suggest.

Thanks
Kamlesh

**Comment by belemaire** [comment]
Hi @kamleshgit 

We have some documentation related to setting up a new Cauldron and using it 
https://electrode.gitbooks.io/electrode-native/platform-parts/cauldron.html#setting-up-a-cauldron

Please let us know if you are able to successfully create and use a Cauldron following this documentation, otherwise we'll offer more help and update our documentation accordingly.

**Comment by deepueg** [comment]
Closing this issue for now. Please re-open if you are still facing issues.
