### ISSUE TITLE
unable to generate a container

### ISSUE THREAD

**Issue by nkratk** [electrode-io/electrode-native#595]
I was trying to generate the container using below command. I didn't face any error but the container wasn't generated. the folder is empty.

**ern create-container —out ~/Downloads/erncontainer1 -p android**

**Comment by belemaire** [comment]
@nkratk 
Sorry for lat answer. Might be a bug related to the use of `~` instead of full path. 
Could you replace the `~` with full path instead (i.e `/Users/your-user-name/Downloads/erncontainer1`) ? 
Will try it out at some point, I think if this is indeed the bug, it might have been fixed in a recent version of Electrode Native (or not) in which case I'll open a proper issue for this one.

**Comment by belemaire** [comment]
This issue was closed as there was no follow up from author for at least 2 weeks.
Feel free to reopen issue if needed.
