### ISSUE TITLE
couldn't install  react-native-ernnavigation-api

### ISSUE THREAD

**Issue by nkratk** [electrode-io/electrode-native#596]
I was trying to install  react-native-ernnavigation-api using 
ern add react-native-ernnavigation-api, it is throwing below error.

react-native-electrode-bridge@1.5.9 plugin is not yet supported. Consider adding support for it to the master manifest.

But when i tried with ern add react-native-ernnavigation-api@0.0.4, it's able to install.

**Comment by belemaire** [comment]
@nkratk 
Sorry for the late answer. I think this has probably been fixed in a recent release.
Please upgrade to latest version of Electrode Native through `ern platform use 0.14.2` and give it a try again. If it's still doesn't work, please clarify a bit more and reopen issue or create a new one.
Thanks.
