### ISSUE TITLE
support for react-native-navigation

### ISSUE THREAD

**Issue by nkratk** [electrode-io/electrode-native#597]
while adding [react-native-navigation](https://github.com/wix/react-native-navigation) as a native module, we are facing some issue. We couldn't add that as an native dependency in our project.

**Comment by deepueg** [comment]
@nkratk We looked into this and found that this native dependency requires you to extend their SplashActivity and Application for it to work for Android. This is a hard dependency for us since we don't mandate on a base activity or an application since EN supports multiple react native apps inside one container.  We might have to contribute back to this native module to make it work with electrode native.

**Comment by belemaire** [comment]
To add on top this. 
While we don't have support for it in our list of supported third party native modules in the Manifest, it is just another third party native module, so with some work you should be able to add it in Electrode Native. Have a look at documentation on [reusing existing native modules](https://electrode.gitbooks.io/electrode-native/platform-parts/manifest.html#reusing-exiting-native-modules) if you want to try going down that road.
Closing this issue as we don't have much more to add on this at this point.
