### ISSUE TITLE
Conflict while generating container.

### ISSUE THREAD

**Issue by deepueg** [electrode-io/electrode-native#619]
Today, if two people tried to generate the container at the same time, the cauldron update fails since the  git push happens on an unsynced local version. This needs to be fixed to avoid conflicts.

**Comment by belemaire** [comment]
This is not an easy problem.

As of now we are using an optimistic concurrency model (offered by some other DB as well) where two users are concurrently running a write operation on the Cauldron, the first one to complete will win. The other one will fail and the user will have to retry.

Alternative DB model is pessimistic concurency, where a lock is acquired by the first user and as long as the lock is held, no other user can perform operation, until the lock is released.

Given our underlying database store (git), pessimistic concurrency is not that easy to achieve (because there is no direct permanent connection to the data store). To use pessimistic locking mechanism, we could create a lock in the cauldron document when first user is running a write command, but then we have no guarantee that this lock will be retrieved by the other user (because of the disconnected model. if `git pull` of the other user is done just before `git push` of the first user to write the lock, then second user will try to write a lock and fail). git is not really appropriate for this model. also with locks we get into this all problems of locks never released etc. going to be hell.

So I think we should remain on current model, without locks. That being said, I think we could look into approach suggested by Krunal being to try to go with auto merge in case the doc was updated by another user first. This might work for most of the use cases, which will make the error probability go down. In case auto merge does not work (conflicts) we can just fail the command as we fail know (even though a more informative message should be done, such as `The Cauldron store was updated during your operation. You should relaunch your command`.

Other way is to use a real fully fledge database and not git, but that's much more work of course (totally off the map for now). 
That might be something to consider though. we might offer a Cassandra or Mongo or what else Cauldron data store, for more large scale enterprise use, in addition to the git data store. git cauldron then can be used for most users that needs to jump in fast without installing a big DB on a dedicated box, and it does suit most use case (even internally, Cauldron concurrency issue have not been a big issue yet and with the auto merge strategy it might be improved).

**Comment by krunalsshah** [comment]
Yes we can look into trying a `git rebase` & if rebase fails, we show the error `The Cauldron store was updated during your operation. You should relaunch your command`

**Comment by belemaire** [comment]
Moving this one to our backlog
