### ISSUE TITLE
Handle pre/post install scripts

### ISSUE THREAD

**Issue by paulmasters** [electrode-io/electrode-native#628]
Sometimes it is necessary to modify a node module slightly for compatibility with RN 0.42 or other module. It's possible to do this with npm by utilising a post install hook, which runs a script after `npm install`.

 For example:
**package.json**
```
{
    "name": "@walmart/react-native-photo",
    "version": "0.5.1",
    "private": false,
    "repository": "https://gecgithub01.walmart.com/react-native/Photo",
    "scripts": {
          "start": "node node_modules/react-native/local-cli/cli.js start",
          "test": "jest --coverage",
          "postinstall": "./patch_node_modules.sh"   /* POST INSTALL SCRIPT */
    },
etc
````
 Here the script `patch_node_modules.sh` applies patches to any modules we need to repair.

It would be great if there was some way to do this for modules added to the electrode native platform.

**Comment by belemaire** [comment]
@paulmasters 
Sorry for late answer.
We already have a way to alter native modules content (if that's what you are trying to achieve) by using a custom manifest plugin configuration. This is not very advanced but does the job when it comes to doing simple string replacement in native modules before they are injected in the Container.
So if this is about patching native modules code, we already support it, and could improve it.
Now if this is about patching any arbitrary node module (in `node_modules`) of a MiniApp, even if it's just a pure JS library, this is a bit more tricky. All MiniApps being packaged together in a Container, they share most of the node modules. We don't really want one MiniApp to alter one the node module it's using, knowing that it could also be used by another MiniApp (once again, with a single MiniApp in isolation this is OK as all node modules are dependencies of this MiniApp only, but when it comes to the composite MiniApp it's tougher).
I would say that this could be OK if this was to be configured at an higher level (like for plugin configuration), maybe at the composite MiniApp level, so that everyone is clear about the patching and what it implies (so that it's not coming from the script of a single MiniApp potentially impacting others, without anyone really knowing about it).
I am not sure I am being clear enough, but in any case, could you please let us know more about the use case where you would have needed (or need) this, so that we can discuss the best approach.
Thanks !

**Comment by jomnius** [comment]
Not my question, but I have a use case:

When building iOS app, I need to modify each xcodeproj file under node_modules and change them so that
- bitcode is turned off (because our app does not use bitcode and this setting has to be in sync between all frameworks) and 
- install_group is set as "everyone" (greetings to Active Directory which sets it by default as "domänen-benutzer" which breaks the build)

```ruby
bc.build_settings['INSTALL_GROUP'] = "everyone"
bc.build_settings['ENABLE_BITCODE'] = "NO"
```

**Comment by belemaire** [comment]
We have starting working on a solution for these concerns as we also need some way to patch code during the container generation lifecycle.

Container generation is composed of multiple steps, but mostly boils down to the following ones :
- Create native container library project and code
- Inject all native dependencies in native library project
- Generate JS Composite project that is composed of all the miniapps
- Generate final JS composite bundle out of this project
- Inject resulting bundle in native container library

Idea would be to expose some hooks in this lifecycle (basically before/after hooks for each step), that could call in some custom user script (for now it'll be JS scripts only, might extend to shell scripts in a subsequent update).

So let's say one need to patch some node_modules after the JS composite project is generated, but before JS bundle is created, it could just be implementing a script with a function `beforeBundling` that will be caled by Electrode Native at this point in time of the container generation process, and this user custom function can do whatever it needs to do.

For jomnius use, it could also be achieved in a script with a function `beforeNativeDependenciesInjection` let's say, that would crawl through all the native dependencies in node_modules and apply custom patching to the .pbxprojs of all these native modules.

We cannot handle all use cases in Electrode Native, so it might be a good way to allow users to take control over some steps of the generation to do custom things. Require a bit more work from the user to properly script things, but at least offer more flexibility to handle most use cases, that might be implemented out of the box later on in Electrode Native, but not there yet.

Will keep you posted.

**Comment by belemaire** [comment]
Moving this one to our backlog
