### ISSUE TITLE
Error in electro native Install command

### ISSUE THREAD

**Issue by kamlesheps** [electrode-io/electrode-native#650]
Hi,

I am trying to install electrode native on windows server 2012 
when I run "**npm install -g electrode-native && ern**" command it starts installation however at some point it throws error. Please see the detailed error below. Also I was able to see that I just got only one folder created in .ern directory and that is "**Versions**" Nothing else appears

C:\Users\MyUserName>npm install -g electrode-native && ern
C:\Users\MyUserName\AppData\Roaming\npm\ern -> C:\Users\MyUserName\AppData\Roami
ng\npm\node_modules\electrode-native\bin\ern.js
+ electrode-native@1.0.12
updated 1 package in 6.6s
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\MyUserName\.ern\.ernrc'

    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at runLocalCli (C:\Users\MyUserName\AppData\Roaming\npm\node_modules\electro
de-native\src\index.js:137:31)
    at Object.<anonymous> (C:\Users\MyUserName\AppData\Roaming\npm\node_modules\
electrode-native\src\index.js:41:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)

Can some one help me please understanding what i would have been doing wrong.

Your help would be deeply appreciated.

Thanks 
Kumar

**Comment by belemaire** [comment]
Hi,

Sorry for the late answer.
F.Y.I we have just release a new patch version of Electrode Native ([0.14.2](https://github.com/electrode-io/electrode-native/releases/tag/v0.14.2) to fix a few Windows related bugs. Maybe the installation error you are facing was due to these bugs.
What I would recommend is the following :

1. Completely uninstall electrode-native from the Windows machine :
  a. Remove the `C:\Users\MyUserName\.ern` directory if it exists
  b. Run `npm uninstall -g electrode-native`
2. Try to reinstall electrode native on the Windows machine through `npm install -g electrode-native && ern`

If you are still experiencing a problem please reopen this issue.

Thanks !
