### ISSUE TITLE
Having trouble loading fonts after upgrading to version v0.14.2

### ISSUE THREAD

**Issue by amloelxer** [electrode-io/electrode-native#669]
Apologies if this has been asked or is blatantly obvious, but React-Native is having trouble accessing my fonts after upgrading my electrode native version from `v0.11.2` to `v0.14.2` using `ern platform use ...`. Currently I have nothing in production, and haven't actually linked against our native iOS App, I'm just developing features right now through using `ern run-ios`.  In my package.json, I specify the fonts directory in `rnpm`. This worked fine in `v0.11.12` but no longer works me as react-native tells me it can't find my font families in `v0.14.2`
<img width="395" alt="screen shot 2018-03-08 at 11 44 40 am" src="https://user-images.githubusercontent.com/5010246/37163557-1cf9132c-22c6-11e8-9fd5-f640b3b5f76b.png">

I come from Native iOS land, so I have checked the Info.plist in the runner, and don't see any fonts specified in the plist as well. 
![screen shot 2018-03-08 at 11 47 28 am](https://user-images.githubusercontent.com/5010246/37163754-90928b42-22c6-11e8-8bbf-86ddb5bc79c8.png)

To remedy this, I have tried deleting the `ios` directory and ran `ern run-ios` again and still receive the same error. I have also tried `rm -rf ~/.ern/containergen/out/ios/ElectrodeContainer/Libraries/ReactNative/third-party/` for good measure but it still doesn't remedy the problem. Any thoughts? 

Electrode native version: `v0.14.2`
Xcode Version: `9.2`
MacOS Version: `10.13.1` 

Many thanks in advance!

**Comment by belemaire** [comment]
Hi @amloelxer,

Thanks for the clean ticket. Helpful for us to know that it was working for you in `0.11.2` but not anymore in `0.14.2`. Will help us pinpoint the issue. We will have to try to reproduce locally and get back to you. 

We have this flag `--ignoreRnpmAssets` for `create-container` command, but you are not using this command. That being said, in the internals of Electrode Native this flag is used for generating any Container generation, even when generating a Container for the Runner (`ern run-ios`). By default it is set to false meaning that rnpm assets are not ignored. Only `create-container` command or Cauldron specific configuration (but you are not using any Cauldron) can turn it on.

Internally we are ignoring rnpm assets for ios as our native team want to control them from the ios native application project, so we are using this flag (that's why maybe if there is an issue with the rnpm assets on iOS we havent noticed it yet as we ignore them using the flag).

That being said, FYI, when not ignoring rnpm assets with Electrode Native (default mode), they are packaged inside the Container Framework, not the application (so even if that was working properly as in 0.11.2, you wouldn't see them in the native application project ;)). Could you please take a look in the Container project if you see the assets there in the ressources and let us know ?

**Comment by amloelxer** [comment]
@belemaire thank you for the prompt response. In the container I see two things. I see this in resources (non of these fonts I manually added to the project). 
![screen shot 2018-03-08 at 1 48 56 pm](https://user-images.githubusercontent.com/5010246/37170054-c596fcf4-22d7-11e8-8027-0384fdb739cd.png)

I also see my image assets here 
![screen shot 2018-03-08 at 1 49 18 pm](https://user-images.githubusercontent.com/5010246/37170114-f2d6118c-22d7-11e8-9c97-f9159a9cf9c3.png)

As for my package.json, the rnpm directory has a path of ```"rnpm": {
    "assets": [
      "./src/assets/fonts"
    ]
  },``` 

With a react-native directory that looks like 
![screen shot 2018-03-08 at 1 53 27 pm](https://user-images.githubusercontent.com/5010246/37170247-533d283a-22d8-11e8-9690-942d452f309e.png)

Do any of this seem wrong or out of the ordinary other than my fonts are not being added to resources?

**Comment by belemaire** [comment]
Thanks for the screenshots.

Interesting to see all these fonts in the Container. They usually come from `react-native-vector-icons` module. Are you using this one by any chance directly (or maybe indirectly, one of your modules might be pulling this one ?).

Anyway that's not related to the problem you are facing. That being said, `react-native-vector-icons` is a good example for rnpm as they are making use of it in their package.json to copy the fonts over.

If you look at [their repo](https://github.com/oblador/react-native-vector-icons), you can see that they have the `Fonts` directory directly at the root (same level as `package.json`) and they declare ["rnpm": { "assets" : [ "Fonts" ] } ](https://github.com/oblador/react-native-vector-icons/blob/master/package.json#L57-L61) in their package.json.

Your path looks about right. That being said I am no sure about the `./` prefix.
As you can see in `react-native-vector-icons` they just use `Fonts` not `./Fonts`.
I think Electrode Native might just be appending the path that is provided so it might result in a weird path. Not sure thought but that might be something to check.

Could you replace `./src/assets/fonts` with `src/assets/fonts` instead and let us know if that changes anything ?

**Comment by amloelxer** [comment]
@belemaire I just checked and I am using `react-native-vector-icons` indirectly. I tried switching to `src/assets/fonts` but that didn't work, and I tried bringing it top level so my `rnpm` looks like `"rnpm": { "assets" : [ "Fonts" ] }` (with the corresponding folder move) and it still didn't work. Is it possible that the `react-native-vector-icons` are doing any overwriting of these existing fonts? Also could you point me to line of code where this copying occurs? If so, I could probably do some debugging on a dev build and at least verify what the problem is with certainty when I have time.

**Comment by belemaire** [comment]
Ok thanks for tying. That was just a quick thought to try before jumping in the code.

Now for the code it seem like we have a regression indeed (starting from `0.12.0`). 
In `0.11.0` [that was the way we were doing it on iOS](https://github.com/electrode-io/electrode-native/blob/v0.11/ern-container-gen/src/generators/ios/IosGenerator.js#L137)

Starting `0.12.0` we've done some refactoring around this and `copyRnpmAssets` is now called [here](https://github.com/electrode-io/electrode-native/blob/v0.14/ern-container-gen/src/generators/ios/IosGenerator.js#L81) during container generation. But the actual implementation [here](https://github.com/electrode-io/electrode-native/blob/788395aaa14c166f888c5aaf7ff62ea6a637b148/ern-container-gen/src/utils.js#L411) is the Android one ... being called by iOS :( No wonder why it fails. Looks like the iOS implementation just disappeared.

Will work on a fix and release a patch version (0.14.3) later on today. We anyway also have another unrelated bug fix that we need to release before 0.15.0 release of Monday.

**Comment by amloelxer** [comment]
Ahh that'll definitely do it. Sounds great. Thank you for being so responsive! Looking forward to eventually using Electrode-Native in production.

**Comment by belemaire** [comment]
@amloelxer 
No problem, thank you for creating such clear issues ;) 
And sorry for the problem. Because we are not having -yet- a large user community, one of the advantages is that we can react relatively quickly on issues (as we are not flooded). The downside of this being that some bugs can remain unnoticed for quite some time, given that we are not internally using all of the features exposed by the platform.

Anyway, issued a PR to fix this issue. We will release `0.14.3` in the morning (PST) tomorrow, still have to check with the team what we have to ship in this one.

In the meantime, you can make a dirty patch if it can't wait : 
In `~/.ern/versions/0.14.2/node_modules/ern-container-gen/dist/utils.js`
replace `('lib', 'src', 'main', 'assets', assetDirectoryName.toLowerCase())` 
with `('ElectrodeContainer', 'Resources')`
As I said it's a dirty path, should only be a temporary if you want to make it work quick on iOS (but will make Android fail on the other hand).

**Comment by belemaire** [comment]
@amloelxer 
F.Y.I just released [0.14.3](https://github.com/electrode-io/electrode-native/releases/tag/v0.14.3) which contain the fix for this issue.

**Comment by amloelxer** [comment]
@belemaire works like a dream. Thanks for the quick release!
