### ISSUE TITLE
Initializing container in Swift

### ISSUE THREAD

**Issue by lindaMedina** [electrode-io/electrode-native#681]
Initializing electrode container with objective-c works fine, however it's not possible to do it from Swift because of the way how the ElectrodePluginConfig protocol is imported  in the ElectrodeReactNative header file, the issue is that the function startWithConfigurations is not visible from Swift at all.

I made small import changes in ElectrodeReactNative.h, ElectrodeBridgeDelegate.h/.m files to fix it however every time I recreate my container I have to override these files again. It would be nice to have those changes in the container hull project.

**Comment by belemaire** [comment]
@lindaMedina 
Thanks for the feedback !

We could potentially review your code changes in the Container and include them in the platform if we see no problem with it, so that you won't have to do the update every time and also it would fix this for other potential users that are/will face the same issue.

Could you open a pull request to Electrode Native for the changes you made in these files ?
Once you clone the repo, all the iOS container files are located in [ern-container-
gen/src/generators/ios/hull/ElectrodeContainer](https://github.com/electrode-io/electrode-native/tree/master/ern-container-gen/src/generators/ios/hull/ElectrodeContainer). They include some mustache templating placeholders for some of them.

If you have any question regarding the changes, or opening a PR, please let us know by replying on this issue.

F.Y.I the iOS engineer who will look into this, will be back on Monday, so no need to rush.

**Comment by androolloyd** [comment]
@lindaMedina could you share how you got this working for swift apps? or @belemaire can you point me into the right direction on changes I would have to make.

**Comment by jomnius** [comment]
ping @lindaMedina just a reminder :)

We got this working by placing manually fixed files into git and then running (below) in build script, AFTER container generation and BEFORE compiling: 

```bash
git checkout -- $MYPATH/ios/ElectrodeContainer/ElectrodeBridgeDelegate.h
git checkout -- $MYPATH/ios/ElectrodeContainer/ElectrodeBridgeDelegate.m
git checkout -- $MYPATH/ios/ElectrodeContainer/ElectrodeReactNative.h
```

I've destroyed the manually fixed files at least once already, so this is not really a future-proof solution...

**Comment by cohen72** [comment]
any progress with this?

**Comment by cohen72** [comment]
For anyone interested (@androolloyd, @jomnius, @lindaMedina, @belemaire), I created a workaround, in which I create an objective-c class called `ElectrodeWrapper`, add it to the bridging header, and call it's `start` method from the `AppDelegate`

**Like This:**

```
// App-Bridging-Header.h

#ifndef Bridging_header_h
#define Bridging_header_h

#import "ElectrodeWrapper.h"

#endif /* Bridging_header_h */

```

```
// ElectrodeWrapper.h

@interface ElectrodeWrap : NSObject
- (void) start;
@end

```

```
// ElectrodeWrapper.m

#import "ElectrodeWrapper.h"
#import <ElectrodeContainer/ElectrodeContainer.h>

@interface ElectrodeWrapper ()
@end

@implementation ElectrodeWrapper

- (void) start {
  ElectrodeContainerConfig *containerConfig = [[ElectrodeContainerConfig alloc] init];
  containerConfig.debugEnabled = YES;
  [ElectrodeReactNative startWithConfigurations:containerConfig];
}

@end
```

```
// AppDelegate.swift

func application(_ application: UIApplication,
                   didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
   ...
   ElectrodeWrapper().start()    
   return true
  }
```

**Comment by belemaire** [comment]
Moving this one to our backlog
