### ISSUE TITLE
[Question] Is possible to create an app using only electrode native.

### ISSUE THREAD

**Issue by RandyHBH** [electrode-io/electrode-native#716]
Hi, guys, I have a question for you, is it possible to build a complete app using only electrode-native, without the need to create a native app to use it with?

**Comment by belemaire** [comment]
Hi Randy,

Short answer : no
Be it for React Native itself or Electrode Native, the JavaScript code of your application has to be "hosted" in a native application in order to run.
That being said, you don't need a pre existing native application to use Electrode Native (or React Native itself). Indeed, if you don't have any existing native application to start from, Electrode Native (or react Native itself for that matter) will scaffold (generate/create) one for you. When using Electrode Native, whenever you run `ern run-android` or `ern run-ios` command, a native application project is created under the hood (in the `ios` and `android` folders). This native application is very minimal though, it mostly contains the minimum needed to host and launch the MiniApp, it will need some modification if you need to host more than one MiniApp in it though.
In the end, even though you need a native application in any case (even if very minimal) you might not have to touch it at all one setup properly and all your coding will be on the JavaScript side only.
