### ISSUE TITLE
Getting framework into existing ios app

### ISSUE THREAD

**Issue by adamweeks** [electrode-io/electrode-native#778]
We've been investigating utilizing electrode-native in an existing iOS application. We were able to build a miniapp, container and cauldron, but so far have been ineffective in starting "Stage 3" in this [doc](https://electrode.gitbooks.io/electrode-native/overview/ern-workflow.html)

Where do we access the framework that is generated by the container in order to use it within our iOS app?

**Comment by adamweeks** [comment]
Sorry about this, found more info in [this](https://electrode.gitbooks.io/electrode-native/platform-parts/container.html#adding-a-container-to-your-mobile-application)

**Comment by belemaire** [comment]
We have a section in the documentation related to [adding a container to your mobile application](https://electrode.gitbooks.io/electrode-native/platform-parts/container.html#adding-a-container-to-your-mobile-application) that might give you some hints.

But as an high level overview, before you git into the documentation, the Container gets generated locally on the machine that triggered the Container generation (it gets generated to the `~/.ern/containergen` directory unless specified otherwise). From there you can manually import the Container Framework project in your native application, but this is of limited use as no one else from the team will have access to it. 

Ideally you'd want the Container to be published to some shared location, so that it can be retrieved by anyone during the native app build. As of today we just have one publisher for iOS Containers : `git`. This publisher will publish a Container to a remote git repository and git tag it with a version. From there you can retrieve it in some way in your native iOS app (either as a Carthage dependency, or manually as a submodule etc..). You can manually trigger a Container publication by using the `ern publish-container` command, or automatically through a Cauldron (with proper configuration for publication), on any Container state change in a Cauldron (for ex when adding or updating a MiniApp in a Container), a Container will automatically be regenerated and published (or through `ern cauldron regen-container` command).
