### ISSUE TITLE
Code-push for a native app version not present in Cauldron.

### ISSUE THREAD

**Issue by deepueg** [electrode-io/electrode-native#804]
Today we need to create a native app version in the cauldron to be able to perform code push OTA. 

Consider the scenario where a native app releases `v6.0.0` with a  container version `container-v1.0.0`.

Subsequent native app releases(`v6.0.1`, `v6.0.2` ..... and so on) would use the same container version if there is no change required. This means that there may not be an entry present in the cauldron for these native app versions. 

Now, if a bug was identified in the later version of the native app and a code push is required to fix it, we need to perform code push for each version of the native app released. 

Today, this requires us to first create all these native app versions in the cauldron. This results in unnecessary container creations and also an overhead for someone who maintains the cauldron configuration. 

Proposed Solution:

One of the proposed solutions is to allow `ern code-push release` command to create new entries in the cauldron if the native app version is not already present. 

This is just an initial thought and we need to further discuss this before finalizing the solution.

**Comment by belemaire** [comment]
I might be wrong but I think the `cauldron add nativeapp` command with `copyover`, does not trigger a new Container generation, it just copies data over so its not that much overhead. That being said, indeed, a shortcut could be as you suggest to couple the copyover with `ern code-push release / promote` commands. In case the target version does not exist (and only if a fixed target version is specified and not a version range) the command will say something like `hey you are trying to push an OTA update to a native app version that Electrode Native don't know about, would you like to create this new version from x.x.x` ? `x.x.x` being the latest native app version cauldron entry in the Cauldron. Then command will just run copy over from previous native app version before doing the CodePush. If the user does not want to do that (maybe because user just mistyped target version) then the command will just abort.
I don't find `add nativeapp` to add a lot of overhead (quick command to run as it doesn't regenerate Container -if it does it shouldn't, thats a bug-) but if there is a strong need/desire for it, then let's do it

**Comment by deepueg** [comment]
You are right, this does not create a container. I was thinking it would, created the ticket before trying it. 

And after doing this for few iterations, here are the steps we need to do.
1. Create a new version of the native app( --copyVersion)
2. Mark them as released
3. Perform code-push release. 

As you suggested, perhaps we can bring this down to only have #3, and exclude the other two steps. Not a pressing need for now.

**Comment by belemaire** [comment]
Yes correct, forgot about step 2 .. so it's actually 3 steps.
Makes a bit more sense then to turn it into 1 step 👍

**Comment by belemaire** [comment]
Moving this one to our backlog
