### ISSUE TITLE
ern run-android fails 

### ISSUE THREAD

**Issue by AkashDeep406** [electrode-io/electrode-native#994]
Currently I'm working on MiniApp, and android build fails when i try ern run-android, with the following error log, I have the following configuration 
React native Version - 0.57
Electrode native version - 0.24.5
Also Im interested to use Typescript in my project , when I use RN version 0.56 , with all the typescript
dependencies , it doesn't seem to resolve App.tsx file , any help on this would be greatly appreciated  :)

 An error occurred: Command failed: ./gradlew lib:uploadArchives
✖
✖ FAILURE: Build failed with an exception.
✖
✖ * What went wrong:
✖ Could not resolve all files for configuration ':lib:releaseCompileClasspath'.
✖ > Could not find com.walmartlabs.ern:react-native:0.57.0.
✖   Searched in the following locations:
✖
file:/Users/ajayasha/Library/Android/sdk/extras/m2repository/com/walmartlabs/ern/react-native/0.57.0/react-native-0.5
7.0.pom
✖
file:/Users/ajayasha/Library/Android/sdk/extras/m2repository/com/walmartlabs/ern/react-native/0.57.0/react-native-0.5
7.0.jar
✖
file:/Users/ajayasha/Library/Android/sdk/extras/google/m2repository/com/walmartlabs/ern/react-native/0.57.0/react-nat
ive-0.57.0.pom
✖
file:/Users/ajayasha/Library/Android/sdk/extras/google/m2repository/com/walmartlabs/ern/react-native/0.57.0/react-nat
ive-0.57.0.jar
✖
file:/Users/ajayasha/Library/Android/sdk/extras/android/m2repository/com/walmartlabs/ern/react-native/0.57.0/react-na
tive-0.57.0.pom
✖
file:/Users/ajayasha/Library/Android/sdk/extras/android/m2repository/com/walmartlabs/ern/react-native/0.57.0/react-na
tive-0.57.0.jar
✖       file:/Users/ajayasha/.m2/repository/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.pom
✖       file:/Users/ajayasha/.m2/repository/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.jar
✖       https://jcenter.bintray.com/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.pom
✖       https://jcenter.bintray.com/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.jar
✖       https://dl.google.com/dl/android/maven2/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.pom
✖       https://dl.google.com/dl/android/maven2/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.jar
✖       https://repo1.maven.org/maven2/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.pom
✖       https://repo1.maven.org/maven2/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.jar
✖       https://jitpack.io/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.pom
✖       https://jitpack.io/com/walmartlabs/ern/react-native/0.57.0/react-native-0.57.0.jar
✖   Required by:
✖       project :lib
✖
✖ * Try:
✖ Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
✖
✖ * Get more help at https://help.gradle.org
✖
✖ BUILD FAILED in 3s
✖

**Comment by belemaire** [comment]
Sorry for not giving quick feedback on this issue.
We don't publish all versions of React Native. 
For `0.57` we only published `0.57.5`.
You can see the list of React Native versions that we support by looking for `react-native@` in our [public manifest](https://github.com/electrode-io/electrode-native-manifest/blob/master/manifest.json).
We always target (add support for) and publish the current React Native version available at the time of a new Electrode Native release, and indicate it in the release notes. We don't publish intermediate React Native versions that are released in between Electrode Native versions.

Also typescript should be somewhat supported now, from https://github.com/electrode-io/electrode-native/pull/1059

Closing this issue now, feel free to reopen if needed

**Comment by santosh2606** [comment]
An error occurred: Command failed: ./gradlew lib:uploadArchives

**Comment by friederbluemle** [comment]
@santosh2606 - Is this error related to this "ern run-android fails" issue? If not please [open a new issue](https://github.com/electrode-io/electrode-native/issues/new) with more information. Thanks!

**Comment by santosh2606** [comment]
Thanks for response Fried, Yes this issue is related to ern run-android. I am using ubuntu 18.04 OS

**Comment by santosh2606** [comment]
@friederbluemle , above issue has been resolved and steps are follows:
1. open the terminal and type sudo su to become the root user
2. Install the gradle
3. Edit the ~/.bashrc and add the followings

export ANDROID_SDK_ROOT=/home/$USER/Android/Sdk   # comment you can also change the $USER with your username or can set the path where you have installed Android
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/tools
export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools
also option in case still getting error add following line as well
GRADLE_HOME=/opt/gradle # comment enter the respective path as you have installed
export PATH=$PATH:$GRADLE_HOME/gradle5.5
4. Save the file
5. Reboot the system
6. again login with root user into the terminal and execute following command once
after connecting the mobile device
$ adb devices 
7. now run the ern run-android command

**Comment by friederbluemle** [comment]
Hi @santosh2606 - Thanks so much for reporting back, and for the detailed steps.
It should not be necessary to install Gradle globally. Every Android project ships with a fully self contained Gradle wrapper that automatically downloads Gradle (if necessary) and uses it locally. Also it should not be necessary to execute any commands as root user.
We will look into what might have caused these issues and will try to improve the experience in the future. 👍

**Comment by santosh2606** [comment]
Hi @friederbluemle , We are also getting issue related to navigation as we are getting error on clicking

received message from JS(data={ NativeMap: {"type":"req","name":"com.ernnavigationApi.ern.api.request.navigate","id":"7b8f2b9e-7693-48cc-8653-b0e7032248e1","data":{"path":"nav.Contact","navigationBar":{"title":"Untitled","buttons":[]},"jsonPayload":"{}"}} })
D/ElectrodeBridgeTransceiver: Received message is a REQUEST(name=com.ernnavigationApi.ern.api.request.navigate), will look for a request handler and forward this request
D/ElectrodeBridgeTransceiver: --> --> --> --> --> Request(id=7b8f2b9e-7693-48cc-8653-b0e7032248e1, name=com.ernnavigationApi.ern.api.request.navigate, isJS=true)
D/ElectrodeBridgeTransceiver: NO_TIMEOUT request, Will skip timeout check for request(name:com.ernnavigationApi.ern.api.request.navigate, id:7b8f2b9e-7693-48cc-8653-b0e7032248e1, data:Bundle[{jsonPayload={}, navigationBar=Bundle[{title=Untitled}], path=nav.Contact}] type:REQUEST)
D/ElectrodeBridgeTransceiver: No handler available to handle the request(id=7b8f2b9e-7693-48cc-8653-b0e7032248e1, name=com.ernnavigationApi.ern.api.request.navigate). Will fail the request
D/ElectrodeBridgeTransceiver: Handling bridge response
D/ElectrodeBridgeTransceiver: completing transaction(7b8f2b9e-7693-48cc-8653-b0e7032248e1)
D/ElectrodeBridgeTransceiver: <-- <-- <-- <-- <-- Response(id=7b8f2b9e-7693-48cc-8653-b0e7032248e1, name=com.ernnavigationApi.ern.api.request.navigate, data=null, error=BridgeFailureMessage-> code:ENOHANDLER, message:No registered request handler found for com.ernnavigationApi.ern.api.request.navigate, exeception:null, debugMessage:null) received
D/ElectrodeBridgeTransceiver: Completing by emitting event to JS since the request was initiated from JS side.
D/ReactContextWrapperInternal: emitting event(id=7b8f2b9e-7693-48cc-8653-b0e7032248e1, name=com.ernnavigationApi.ern.api.request.navigate, type=RESPONSE) to JS

Please look and guide us to resolve
